/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.loginUI;

import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import my.appUI.AppUI;

/**
 * Klasa obsługująca logowanie i rejestrację
 * Pobiera dane użytkownika z tabli users
 * Wpisuje dane użytkownika do tabeli usres
 * @author kusmi
 */
public class LoginUI extends javax.swing.JFrame {

    /**
     * Creates new form LoginUI
     */
    public LoginUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        loginPanel = new javax.swing.JPanel();
        lTitlePanel = new javax.swing.JPanel();
        lTitleLabel = new javax.swing.JLabel();
        lInputPanel = new javax.swing.JPanel();
        lUsernameLabel = new javax.swing.JLabel();
        lPasswordLabel = new javax.swing.JLabel();
        lUsernameField = new javax.swing.JTextField();
        lPasswordField = new javax.swing.JPasswordField();
        lsubmitPanel = new javax.swing.JPanel();
        lSubmitButton = new javax.swing.JButton();
        lRegisterButton = new javax.swing.JButton();
        registerPanel = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        inputPanel = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        submitPanel = new javax.swing.JPanel();
        registerButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(248, 248, 248));
        setPreferredSize(new java.awt.Dimension(815, 630));

        mainPanel.setBackground(new java.awt.Color(220, 53, 53));
        mainPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        mainPanel.setLayout(new java.awt.CardLayout());

        loginPanel.setBackground(new java.awt.Color(247, 247, 247));
        loginPanel.setMaximumSize(new java.awt.Dimension(800, 600));
        loginPanel.setPreferredSize(new java.awt.Dimension(800, 600));

        lTitlePanel.setBackground(new java.awt.Color(220, 53, 53));

        lTitleLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lTitleLabel.setForeground(new java.awt.Color(248, 248, 248));
        lTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTitleLabel.setText("Login");

        javax.swing.GroupLayout lTitlePanelLayout = new javax.swing.GroupLayout(lTitlePanel);
        lTitlePanel.setLayout(lTitlePanelLayout);
        lTitlePanelLayout.setHorizontalGroup(
            lTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lTitlePanelLayout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(lTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lTitlePanelLayout.setVerticalGroup(
            lTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lTitlePanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lTitleLabel)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        lInputPanel.setBackground(new java.awt.Color(247, 247, 247));
        lInputPanel.setPreferredSize(new java.awt.Dimension(751, 331));

        lUsernameLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lUsernameLabel.setForeground(new java.awt.Color(220, 53, 53));
        lUsernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lUsernameLabel.setLabelFor(lUsernameField);
        lUsernameLabel.setText("Nazwa użytkownika:");

        lPasswordLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lPasswordLabel.setForeground(new java.awt.Color(220, 53, 53));
        lPasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lPasswordLabel.setLabelFor(lPasswordField);
        lPasswordLabel.setText("Hasło:");

        lUsernameField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lUsernameField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(220, 53, 53), 1, true));

        lPasswordField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lPasswordField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(220, 53, 53), 1, true));

        javax.swing.GroupLayout lInputPanelLayout = new javax.swing.GroupLayout(lInputPanel);
        lInputPanel.setLayout(lInputPanelLayout);
        lInputPanelLayout.setHorizontalGroup(
            lInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lInputPanelLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(lInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lUsernameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(lInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        lInputPanelLayout.setVerticalGroup(
            lInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lInputPanelLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(lInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lUsernameLabel)
                    .addComponent(lUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94)
                .addGroup(lInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPasswordLabel)
                    .addComponent(lPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        lsubmitPanel.setBackground(new java.awt.Color(247, 247, 247));

        lSubmitButton.setBackground(new java.awt.Color(220, 53, 53));
        lSubmitButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lSubmitButton.setForeground(new java.awt.Color(248, 248, 248));
        lSubmitButton.setText("Zaloguj");
        lSubmitButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(220, 53, 53), 1, true));
        lSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lSubmitButtonActionPerformed(evt);
            }
        });

        lRegisterButton.setBackground(new java.awt.Color(248, 248, 248));
        lRegisterButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lRegisterButton.setForeground(new java.awt.Color(220, 53, 53));
        lRegisterButton.setText("Rejestracja");
        lRegisterButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(220, 53, 53), 1, true));
        lRegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lRegisterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lsubmitPanelLayout = new javax.swing.GroupLayout(lsubmitPanel);
        lsubmitPanel.setLayout(lsubmitPanelLayout);
        lsubmitPanelLayout.setHorizontalGroup(
            lsubmitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lsubmitPanelLayout.createSequentialGroup()
                .addGap(343, 343, 343)
                .addGroup(lsubmitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lRegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lsubmitPanelLayout.setVerticalGroup(
            lsubmitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lsubmitPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lRegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lsubmitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lTitlePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lInputPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE))
                .addContainerGap())
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lsubmitPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(loginPanel, "loginPanel");

        registerPanel.setBackground(new java.awt.Color(247, 247, 247));

        titlePanel.setBackground(new java.awt.Color(220, 53, 53));

        titleLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(248, 248, 248));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Rejestracja");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(250, 250, 250))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(titleLabel)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        inputPanel.setBackground(new java.awt.Color(247, 247, 247));

        usernameLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(220, 53, 53));
        usernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        usernameLabel.setText("Nazwa użytkownika:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(220, 53, 53));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Hasło:");

        usernameField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        usernameField.setForeground(new java.awt.Color(220, 53, 53));
        usernameField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(220, 53, 53), 1, true));

        passwordField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        passwordField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(220, 53, 53), 1, true));

        javax.swing.GroupLayout inputPanelLayout = new javax.swing.GroupLayout(inputPanel);
        inputPanel.setLayout(inputPanelLayout);
        inputPanelLayout.setHorizontalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        inputPanelLayout.setVerticalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92))
        );

        submitPanel.setBackground(new java.awt.Color(247, 247, 247));

        registerButton.setBackground(new java.awt.Color(220, 53, 53));
        registerButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        registerButton.setForeground(new java.awt.Color(247, 247, 247));
        registerButton.setText("Zarejestruj");
        registerButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(220, 53, 53), 1, true));
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        loginButton.setBackground(new java.awt.Color(247, 247, 247));
        loginButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        loginButton.setForeground(new java.awt.Color(220, 53, 53));
        loginButton.setText("Logowanie");
        loginButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(220, 53, 53), 1, true));
        loginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout submitPanelLayout = new javax.swing.GroupLayout(submitPanel);
        submitPanel.setLayout(submitPanelLayout);
        submitPanelLayout.setHorizontalGroup(
            submitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(submitPanelLayout.createSequentialGroup()
                .addGap(330, 330, 330)
                .addGroup(submitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        submitPanelLayout.setVerticalGroup(
            submitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(submitPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout registerPanelLayout = new javax.swing.GroupLayout(registerPanel);
        registerPanel.setLayout(registerPanelLayout);
        registerPanelLayout.setHorizontalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titlePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(submitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        registerPanelLayout.setVerticalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submitPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(registerPanel, "registerPanel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lSubmitButtonActionPerformed
        String dbaseURL = "jdbc:postgresql://localhost:5432/u8kusm";
        String dbUsername = "u8kusm";
        String dbPassword = "8kusm";        
        try ( Connection connection = DriverManager.getConnection(dbaseURL, dbUsername, dbPassword);  PreparedStatement st = connection.prepareStatement("SELECT user_id, email, admin_privileges FROM project.users WHERE email=? AND pass=?");) {            
            st.setString(1, lUsernameField.getText());
            st.setString(2, String.valueOf(lPasswordField.getPassword()));
            ResultSet rs = st.executeQuery();
            
            if (rs.next()) {
                dispose();
                String user = (String)rs.getObject(2);
                String admin = ((Integer)rs.getObject(3)).toString();
                AppUI home = new AppUI(user, admin);
                home.setVisible(true);
            }
        } catch (SQLException sqle) {
            sqle.printStackTrace();
        }
    }//GEN-LAST:event_lSubmitButtonActionPerformed

    private void lRegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lRegisterButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "registerPanel");
    }//GEN-LAST:event_lRegisterButtonActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        String dbaseURL = "jdbc:postgresql://localhost:5432/u8kusm";
                String dbUsername  = "u8kusm";
                String dbPassword  = "8kusm"; 
                try(Connection connection = DriverManager.getConnection(dbaseURL, dbUsername, dbPassword);
                    PreparedStatement st = connection.prepareStatement("INSERT INTO project.users(user_id, email, fname, lname, pass, admin_privileges) VALUES (DEFAULT, ?, ?, ?, ?, 0)");
                ){   
                    st.setString(1, usernameField.getText());
                    st.setString(2, "");
                    st.setString(3, "");
                    st.setString(4, String.valueOf(passwordField.getPassword()));
                    
                    if(st.executeUpdate() != 0) {
                        JOptionPane.showMessageDialog(null, "Account Created");
                    }
                    else {
                        JOptionPane.showMessageDialog(null, "Couldnt Create");
                    }
                }
                catch (SQLException sqle) {
                    sqle.printStackTrace();
                    
                    JOptionPane.showMessageDialog(null, sqle.getMessage());
                }
    }//GEN-LAST:event_registerButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "loginPanel");
    }//GEN-LAST:event_loginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel inputPanel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel lInputPanel;
    private javax.swing.JPasswordField lPasswordField;
    private javax.swing.JLabel lPasswordLabel;
    private javax.swing.JButton lRegisterButton;
    private javax.swing.JButton lSubmitButton;
    private javax.swing.JLabel lTitleLabel;
    private javax.swing.JPanel lTitlePanel;
    private javax.swing.JTextField lUsernameField;
    private javax.swing.JLabel lUsernameLabel;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPanel lsubmitPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton registerButton;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JPanel submitPanel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
